### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by spaceVStab**

### CODE REVIEW

**Comment by Abhey** [comment]
Please make README.md more informative. Also now the features like auto-indentation and code highlighting are implemented. In the README add about features of this IDE and how to execute the final release.

**Comment by Abhey** [comment]
Please take a look at all the features and then create a more informative README file.

**Comment by jeffreyng99** [comment]
I'm getting an error whenever I try to push the changes I've made.
remote: Permission to Abhey/C-IDE.git denied to NgJeffrey.
fatal: unable to access 'https://github.com/Abhey/C-IDE.git/': The requested URL returned error: 403

**Comment by Abhey** [comment]
@NgJeffrey  push the changes to your own repository and then create a pull request to this repository. I will then merge it.

**Comment by jeffreyng99** [comment]
@Abhey I just made a new repository and merged my branch onto master. Whenever I click the green "create pull request button", it does not give me the option to create a request with my repository.

**Pull request closed without merging**
